services:
  back-users:
    image: python:3.9  # Use the base Python image
    container_name: back-users
    working_dir: /app
    environment:
      DB_URI: postgresql://cwfvbvxl:jtsNDRjbVqGeBgYcYvxGps3LLlX_t-P5@berry.db.elephantsql.com:5432/cwfvbvxl
      GATEWAY_URL: https://gateway-api-service-merok23.cloud.okteto.net
      RABBITMQ_URL: amqps://skglvayb:RVulev-DurTkD_kARAFR5idNzUPqO88T@jackal.rmq.cloudamqp.com/skglvayb
      UPTRACE_DSN: https://SAe6OtAs8ysrYmkJmM8t-Q@api.uptrace.dev?grpc=4317
    ports:
      - "8000:8000"
    command: bash -c "pip install --no-cache-dir -r requirements.txt && uvicorn control.controller:app --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app