version: '3.9'
services:
  back-users:
    image: python:3.9  # Use the base Python image
    container_name: back-users
    volumes:
      - .:/app
    environment:
      DB_URI: postgresql://cwfvbvxl:jtsNDRjbVqGeBgYcYvxGps3LLlX_t-P5@berry.db.elephantsql.com:5432/cwfvbvxl
    ports:
      - "8000:8000"
      