"""intentando cambiar el valor de profile_picture a String

Revision ID: 13267b22c216
Revises: c1ca0baa8eb5
Create Date: 2023-09-19 14:50:36.134389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13267b22c216'
down_revision = 'c1ca0baa8eb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
