"""intentando cambiar el valor de profile_picture a String2

Revision ID: 79c6779d35e3
Revises: 13267b22c216
Create Date: 2023-09-19 14:52:30.584337

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '79c6779d35e3'
down_revision = '13267b22c216'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.String(length=600), nullable=True))
    op.drop_column('users', 'profile_picture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_picture', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###
