# pylint: skip-file

"""Prueba numero tres

Revision ID: 84d667de3693
Revises: d19b7c9f55fe
Create Date: 2023-09-21 12:04:16.948765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "84d667de3693"
down_revision: Union[str, None] = "d19b7c9f55fe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
