"""prueba(no es nada)

Revision ID: c1ca0baa8eb5
Revises: dd425b17a545
Create Date: 2023-09-19 14:45:37.235454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1ca0baa8eb5'
down_revision = 'dd425b17a545'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
