name: Database Migration

on:
  push:
    branches:
      - main
jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run database migration
        run: |
            export DB_URI=${{ secrets.DB_URI }}
            alembic -c repository/alembic.ini upgrade head
