# File: .github/workflows/workflow.yml
# pull_request:
#   branches:
#     - master
on:
    push:
name: Deploy-Service (Okteto + Migrations)  
jobs:
    devflow:
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@master
        - name: context
          uses: okteto/context@latest
          with:
            token: ${{ secrets.OKTETO_TOKEN }}
        - name: "Activate Namespace"
          uses: okteto/namespace@latest
          with:
            name: merok23
        - name: "Trigger the pipeline"
          uses: okteto/pipeline@latest
          with:
            name: pr-${{ github.event.number }}
            timeout: 8m
            skipIfExists: true
            variables: "DB_HOST=mysql,CONFIG_PATH=/tmp/config.yaml"
  